// (C) Uri Wilensky. https://github.com/NetLogo/NetLogo

package org.nlogo.core

import Syntax._

object Syntaxes {
  val syntaxes = A.syntaxes ++ B.syntaxes
}

object A {
  val syntaxes = Map[String, Syntax](
    ("_breed", reporterSyntax(ret = AgentsetType)),
    ("_return", commandSyntax()),
    ("_goto", commandSyntax()),
    ("_unaryminus", reporterSyntax(right = List(NumberType), ret = NumberType)),
    ("_countwith", reporterSyntax(right = List(AgentsetType, BooleanBlockType), ret = NumberType, agentClassString = "OTPL", blockAgentClassString = "?")),
    ("_countotherwith", reporterSyntax(right = List(AgentsetType, BooleanBlockType), ret = NumberType, agentClassString = "OTPL", blockAgentClassString = "?")),
    ("_repeatinternal", commandSyntax()),
    ("_repeatlocalinternal", commandSyntax()),
    ("_repeatlocal", commandSyntax(right = List(NumberType, CommandBlockType))),
    ("_returnreport", commandSyntax()),
    ("_fd1", commandSyntax(agentClassString = "-T--", switches = true)),
    ("_fdinternal", commandSyntax(right = List(WildcardType), switches = true)),
    ("_crtfast", commandSyntax(right = List(NumberType), agentClassString = "O---", switches = true)),
    ("_crofast", commandSyntax(right = List(NumberType), agentClassString = "O---", switches = true)),
    ("_sproutfast", commandSyntax(right = List(NumberType), agentClassString = "--P-", switches = true)),
    ("_setobservervariable", commandSyntax(right = List(WildcardType), switches = true)),
    ("_setpatchvariable", commandSyntax(right = List(WildcardType), agentClassString = "-TP-", switches = true)),
    ("_setturtlevariable", commandSyntax(right = List(WildcardType), agentClassString = "-T--", switches = true)),
    ("_setlinkvariable", commandSyntax(right = List(WildcardType), agentClassString = "---L", switches = true)),
    ("_setbreedvariable", commandSyntax(right = List(WildcardType), agentClassString = "-T--", switches = true)),
    ("_breedhere", reporterSyntax(ret = TurtlesetType, agentClassString = "-TP-")),
    ("_setturtleorlinkvariable", commandSyntax(right = List(WildcardType), agentClassString = "-T-L", switches = true)),
    ("_turtlevariableof", reporterSyntax(right = List(TurtleType | TurtlesetType), ret = WildcardType)),
    ("_breedvariableof", reporterSyntax(right = List(TurtleType | TurtlesetType), ret = WildcardType)),
    ("_patchvariableof", reporterSyntax(right = List(TurtleType | PatchType | TurtlesetType | PatchsetType), ret = WildcardType)),
    ("_patchvariabledouble", reporterSyntax(ret = NumberType, agentClassString = "-TP-")),
    ("_setprocedurevariable", commandSyntax(right = List(WildcardType))),
    ("_randomconst", reporterSyntax(ret = NumberType)),
    ("_constdouble", reporterSyntax(ret = NumberType)),
    ("_constlist", reporterSyntax(ret = ListType)),
    ("_constboolean", reporterSyntax(ret = BooleanType)),
    ("_conststring", reporterSyntax(ret = StringType)),
    ("_nobody", reporterSyntax(ret = NobodyType)),
    ("_observervariable", reporterSyntax(ret = WildcardType | ReferenceType)),
    ("_letvariable", reporterSyntax(ret = WildcardType)),
    ("_patchvariable", reporterSyntax(ret = WildcardType | ReferenceType, agentClassString = "-TP-")),
    ("_turtleorlinkvariable", reporterSyntax(ret = WildcardType | ReferenceType, agentClassString = "-T-L")),
    ("_turtlevariable", reporterSyntax(ret = WildcardType | ReferenceType, agentClassString = "-T--")),
    ("_linkvariable", reporterSyntax(ret = WildcardType | ReferenceType, agentClassString = "---L")),
    ("_breedvariable", reporterSyntax(ret = WildcardType | ReferenceType, agentClassString = "-T--")),
    ("_turtlevariabledouble", reporterSyntax(ret = NumberType, agentClassString = "-T--")),
    ("_taskvariable", reporterSyntax(ret = WildcardType)),
    ("_procedurevariable", reporterSyntax(ret = WildcardType)),
    ("_commandtask", reporterSyntax(ret = CommandTaskType)),
    ("_reportertask", reporterSyntax(ret = ReporterTaskType)),
    ("_breedsingular", reporterSyntax(right = List(NumberType), ret = TurtleType | NobodyType)),
    ("_patchwest", reporterSyntax(ret = PatchType, agentClassString = "-TP-")),
    ("_patcheast", reporterSyntax(ret = PatchType, agentClassString = "-TP-")),
    ("_patchnorth", reporterSyntax(ret = PatchType, agentClassString = "-TP-")),
    ("_patchsouth", reporterSyntax(ret = PatchType, agentClassString = "-TP-")),
    ("_patchne", reporterSyntax(ret = PatchType, agentClassString = "-TP-")),
    ("_patchnw", reporterSyntax(ret = PatchType, agentClassString = "-TP-")),
    ("_patchse", reporterSyntax(ret = PatchType, agentClassString = "-TP-")),
    ("_patchsw", reporterSyntax(ret = PatchType, agentClassString = "-TP-")),
    ("_countother", reporterSyntax(right = List(AgentsetType), ret = NumberType, agentClassString = "-TPL")),
    ("_otherwith", reporterSyntax(right = List(AgentsetType, BooleanBlockType), ret = AgentsetType, agentClassString = "OTPL", blockAgentClassString = "?")),
    ("_recursefast", commandSyntax()),
    ("_anywith", reporterSyntax(right = List(AgentsetType, BooleanBlockType), ret = BooleanType, agentClassString = "OTPL", blockAgentClassString = "?")),
    ("_anyotherwith", reporterSyntax(right = List(AgentsetType, BooleanBlockType), ret = BooleanType, agentClassString = "OTPL", blockAgentClassString = "?")),
    ("_nsum", reporterSyntax(right = List(ReferenceType), ret = NumberType, agentClassString = "-TP-")),
    ("_nsum4", reporterSyntax(right = List(ReferenceType), ret = NumberType, agentClassString = "-TP-")),
    ("_linkbreed", reporterSyntax(ret = LinksetType)),
    ("_setletvariable", commandSyntax(right = List(WildcardType))),
    ("_breedon", reporterSyntax(right = List(TurtleType | PatchType | TurtlesetType | PatchsetType), ret = TurtlesetType)),
    ("_turtleorlinkvariableof", reporterSyntax(right = List(LinkType | LinksetType | TurtleType | TurtlesetType), ret = WildcardType)),
    ("_isbreed", reporterSyntax(right = List(WildcardType), ret = BooleanType)),
    ("_hatchfast", commandSyntax(right = List(NumberType), agentClassString = "-T--", switches = true)),
    ("_linkbreedvariable", reporterSyntax(ret = WildcardType | ReferenceType, agentClassString = "---L")),
    ("_linkbreedsingular", reporterSyntax(right = List(NumberType, NumberType), ret = LinkType | NobodyType)),
    ("_linkvariableof", reporterSyntax(right = List(LinkType | LinksetType), ret = WildcardType)),
    ("_setlinkbreedvariable", commandSyntax(right = List(WildcardType), agentClassString = "---L", switches = true)),
    ("_waitinternal", commandSyntax(switches = true)),
    ("_oneofwith", reporterSyntax(right = List(AgentsetType, BooleanBlockType), ret = AgentType | NobodyType, blockAgentClassString = "?")),
    ("_patchhereinternal", reporterSyntax(ret = PatchType, agentClassString = "-TP-")),
    ("_anyother", reporterSyntax(right = List(AgentsetType), ret = BooleanType, agentClassString = "-TPL")),
    ("_breedat", reporterSyntax(right = List(NumberType, NumberType), ret = TurtlesetType, agentClassString = "-TP-")),
    ("_linkbreedvariableof", reporterSyntax(right = List(LinkType | LinksetType), ret = WildcardType))
  )
}

object B {
  val syntaxes = Map[String, Syntax](
    ("_abs", reporterSyntax(right = List(NumberType), ret = NumberType)),
    ("_acos", reporterSyntax(right = List(NumberType), ret = NumberType)),
    ("_all", reporterSyntax(right = List(AgentsetType, BooleanBlockType), ret = BooleanType, blockAgentClassString = "?")),
    ("_and", reporterSyntax(precedence = NormalPrecedence - 6, left = BooleanType, right = List(BooleanType), ret = BooleanType)),
    ("_any", reporterSyntax(right = List(AgentsetType), ret = BooleanType)),
    ("_approximatehsb", reporterSyntax(right = List(NumberType, NumberType, NumberType), ret = NumberType)),
    ("_approximatergb", reporterSyntax(right = List(NumberType, NumberType, NumberType), ret = NumberType)),
    ("_asin", reporterSyntax(right = List(NumberType), ret = NumberType)),
    ("_ask", commandSyntax(right = List(AgentsetType | AgentType, CommandBlockType), blockAgentClassString = "?", switches = true)),
    ("_askconcurrent", commandSyntax(right = List(AgentsetType, CommandBlockType), blockAgentClassString = "?", switches = true)),
    ("_atan", reporterSyntax(right = List(NumberType, NumberType), ret = NumberType)),
    ("_atpoints", reporterSyntax(precedence = NormalPrecedence + 2, left = TurtlesetType | PatchsetType, right = List(ListType), ret = AgentsetType)),
    ("_autoplot", reporterSyntax(ret = BooleanType)),
    ("_autoplotoff", commandSyntax()),
    ("_autoploton", commandSyntax()),
    ("_basecolors", reporterSyntax(ret = ListType)),
    ("_beep", commandSyntax()),
    ("_behaviorspacerunnumber", reporterSyntax(ret = NumberType)),
    ("_bench", commandSyntax(right = List(NumberType, NumberType), agentClassString = "O---")),
    ("_bk", commandSyntax(right = List(NumberType), agentClassString = "-T--")),
    ("_boom", reporterSyntax(ret = WildcardType)),
    ("_bothends", reporterSyntax(ret = AgentsetType, agentClassString = "---L")),
    ("_butfirst", reporterSyntax(right = List(StringType | ListType), ret = StringType | ListType)),
    ("_butlast", reporterSyntax(right = List(StringType | ListType), ret = StringType | ListType)),
    ("_canmove", reporterSyntax(right = List(NumberType), ret = BooleanType, agentClassString = "-T--")),
    ("_carefully", commandSyntax(right = List(CommandBlockType, CommandBlockType))),
    ("_ceil", reporterSyntax(right = List(NumberType), ret = NumberType)),
    ("_changetopology", commandSyntax(right = List(BooleanType, BooleanType))),
    ("_checksum", reporterSyntax(ret = StringType, agentClassString = "O---")),
    ("_checksyntax", reporterSyntax(right = List(StringType), ret = StringType)),
    ("_clearall", commandSyntax(agentClassString = "O---", switches = true)),
    ("_clearallandresetticks", commandSyntax(agentClassString = "O---", switches = true)),
    ("_clearallplots", commandSyntax()),
    ("_cleardrawing", commandSyntax(agentClassString = "O---", switches = true)),
    ("_clearglobals", commandSyntax(agentClassString = "O---", switches = true)),
    ("_clearlinks", commandSyntax(agentClassString = "O---", switches = true)),
    ("_clearoutput", commandSyntax()),
    ("_clearpatches", commandSyntax(agentClassString = "O---", switches = true)),
    ("_clearplot", commandSyntax()),
    ("_clearticks", commandSyntax(agentClassString = "O---", switches = true)),
    ("_clearturtles", commandSyntax(agentClassString = "O---", switches = true)),
    ("_cos", reporterSyntax(right = List(NumberType), ret = NumberType)),
    ("_count", reporterSyntax(right = List(AgentsetType), ret = NumberType)),
    ("_createlinkfrom", commandSyntax(right = List(TurtleType, CommandBlockType | OptionalType),
      agentClassString = "-T--", blockAgentClassString = "---L", switches = true)),
    ("_createlinksfrom", commandSyntax(right = List(TurtlesetType, CommandBlockType | OptionalType),
      agentClassString = "-T--", blockAgentClassString = "---L", switches = true)),
    ("_createlinksto", commandSyntax(right = List(TurtlesetType, CommandBlockType | OptionalType),
      agentClassString = "-T--", blockAgentClassString = "---L", switches = true)),
    ("_createlinkswith", commandSyntax(right = List(TurtlesetType, CommandBlockType | OptionalType),
      agentClassString = "-T--", blockAgentClassString = "---L", switches = true)),
    ("_createlinkto", commandSyntax(right = List(TurtleType, CommandBlockType | OptionalType),
      agentClassString = "-T--", blockAgentClassString = "---L", switches = true)),
    ("_createlinkwith", commandSyntax(right = List(TurtleType, CommandBlockType | OptionalType),
      agentClassString = "-T--", blockAgentClassString = "---L", switches = true)),
    ("_createorderedturtles", commandSyntax(right = List(NumberType, CommandBlockType | OptionalType),
      agentClassString = "O---", blockAgentClassString = "-T--", switches = true)),
    ("_createtemporaryplotpen", commandSyntax(right = List(StringType))),
    ("_createturtles", commandSyntax(right = List(NumberType, CommandBlockType | OptionalType),
      agentClassString = "O---", blockAgentClassString = "-T--", switches = true)),
    ("_dateandtime", reporterSyntax(ret = StringType)),
    ("_die", commandSyntax(agentClassString = "-T-L", switches = true)),
    ("_diffuse", commandSyntax(right = List(ReferenceType, NumberType), agentClassString = "O---", switches = true)),
    ("_diffuse4", commandSyntax(right = List(ReferenceType, NumberType), agentClassString = "O---", switches = true)),
    ("_display", commandSyntax(switches = true)),
    ("_distance", reporterSyntax(right = List(TurtleType | PatchType), ret = NumberType, agentClassString = "-TP-")),
    ("_distancenowrap", reporterSyntax(right = List(TurtleType | PatchType), ret = NumberType, agentClassString = "-TP-")),
    ("_distancexy", reporterSyntax(right = List(NumberType, NumberType), ret = NumberType, agentClassString = "-TP-")),
    ("_distancexynowrap", reporterSyntax(right = List(NumberType, NumberType), ret = NumberType, agentClassString = "-TP-")),
    ("_div", reporterSyntax(precedence = NormalPrecedence - 2, left = NumberType, right = List(NumberType), ret = NumberType)),
    ("_done", commandSyntax()),
    ("_downhill", commandSyntax(right = List(ReferenceType), agentClassString = "-T--", switches = true)),
    ("_downhill4", commandSyntax(right = List(ReferenceType), agentClassString = "-T--", switches = true)),
    ("_dump", reporterSyntax(ret = StringType, agentClassString = "O---")),
    ("_dump1", reporterSyntax(ret = StringType)),
    ("_dumpextensionprims", reporterSyntax(ret = StringType)),
    ("_dumpextensions", reporterSyntax(ret = StringType)),
    ("_dx", reporterSyntax(ret = NumberType, agentClassString = "-T--")),
    ("_dy", reporterSyntax(ret = NumberType, agentClassString = "-T--")),
    ("_empty", reporterSyntax(right = List(StringType | ListType), ret = BooleanType)),
    ("_equal", reporterSyntax(precedence = NormalPrecedence - 5, left = WildcardType, right = List(WildcardType), ret = BooleanType)),
    ("_error", commandSyntax(right = List(WildcardType))),
    ("_errormessage", reporterSyntax(ret = StringType)),
    ("_every", commandSyntax(right = List(NumberType, CommandBlockType), switches = true)),
    ("_exp", reporterSyntax(right = List(NumberType), ret = NumberType)),
    ("_experimentstepend", commandSyntax(agentClassString = "O---")),
    ("_exportdrawing", commandSyntax(right = List(StringType))),
    ("_exportinterface", commandSyntax(right = List(StringType))),
    ("_exportoutput", commandSyntax(right = List(StringType))),
    ("_exportplot", commandSyntax(right = List(StringType, StringType))),
    ("_exportplots", commandSyntax(right = List(StringType))),
    ("_exportview", commandSyntax(right = List(StringType))),
    ("_exportworld", commandSyntax(right = List(StringType))),
    ("_extracthsb", reporterSyntax(right = List(NumberType | ListType), ret = ListType)),
    ("_extractrgb", reporterSyntax(right = List(NumberType), ret = ListType)),
    ("_face", commandSyntax(right = List(TurtleType | PatchType), agentClassString = "-T--", switches = true)),
    ("_facenowrap", commandSyntax(right = List(TurtleType | PatchType), agentClassString = "-T--", switches = true)),
    ("_facexy", commandSyntax(right = List(NumberType, NumberType), agentClassString = "-T--", switches = true)),
    ("_facexynowrap", commandSyntax(right = List(NumberType, NumberType), agentClassString = "-T--", switches = true)),
    ("_fd", commandSyntax(right = List(NumberType), agentClassString = "-T--")),
    ("_fileatend", reporterSyntax(ret = BooleanType)),
    ("_fileclose", commandSyntax()),
    ("_filecloseall", commandSyntax()),
    ("_filedelete", commandSyntax(right = List(StringType))),
    ("_fileexists", reporterSyntax(right = List(StringType), ret = BooleanType)),
    ("_fileflush", commandSyntax()),
    ("_fileopen", commandSyntax(right = List(StringType))),
    ("_fileprint", commandSyntax(right = List(WildcardType))),
    ("_fileread", reporterSyntax(ret = ReadableType)),
    ("_filereadchars", reporterSyntax(right = List(NumberType), ret = StringType)),
    ("_filereadline", reporterSyntax(ret = StringType)),
    ("_fileshow", commandSyntax(right = List(WildcardType))),
    ("_filetype", commandSyntax(right = List(WildcardType))),
    ("_filewrite", commandSyntax(right = List(ReadableType))),
    ("_filter", reporterSyntax(right = List(ReporterTaskType, ListType), ret = ListType)),
    ("_first", reporterSyntax(right = List(StringType | ListType), ret = WildcardType)),
    ("_floor", reporterSyntax(right = List(NumberType), ret = NumberType)),
    ("_follow", commandSyntax(right = List(TurtleType), agentClassString = "O---", switches = true)),
    ("_followme", commandSyntax(agentClassString = "-T--", switches = true)),
    ("_foreach", commandSyntax(right = List(ListType | RepeatableType, CommandTaskType), defaultOption = Some(2))),
    ("_foreverbuttonend", commandSyntax(switches = true)),
    ("_fput", reporterSyntax(right = List(WildcardType, ListType), ret = ListType)),
    ("_git", commandSyntax(right = List(StringType), agentClassString = "O---")),
    ("_greaterorequal", reporterSyntax(precedence = NormalPrecedence - 4, left = AgentType | NumberType | StringType,
      right = List(AgentType | NumberType | StringType), ret = BooleanType)),
    ("_greaterthan", reporterSyntax(precedence = NormalPrecedence - 4, left = AgentType | NumberType | StringType,
      right = List(AgentType | NumberType | StringType), ret = BooleanType)),
    ("_hatch", commandSyntax(right = List(NumberType, CommandBlockType | OptionalType),
      agentClassString = "-T--", blockAgentClassString = "-T--", switches = true)),
    ("_hidelink", commandSyntax(agentClassString = "---L", switches = true)),
    ("_hideturtle", commandSyntax(agentClassString = "-T--", switches = true)),
    ("_histogram", commandSyntax(right = List(ListType))),
    ("_home", commandSyntax(agentClassString = "-T--", switches = true)),
    ("_hsb", reporterSyntax(right = List(NumberType, NumberType, NumberType), ret = ListType)),
    ("_if", commandSyntax(right = List(BooleanType, CommandBlockType))),
    ("_ifelse", commandSyntax(right = List(BooleanType, CommandBlockType, CommandBlockType))),
    ("_ifelsevalue", reporterSyntax(right = List(BooleanType, ReporterBlockType, ReporterBlockType), ret = WildcardType)),
    ("_ignore", commandSyntax(right = List(WildcardType))),
    ("_importdrawing", commandSyntax(right = List(StringType), agentClassString = "O---", switches = true)),
    ("_importpatchcolors", commandSyntax(right = List(StringType), agentClassString = "O---", switches = true)),
    ("_importpcolorsrgb", commandSyntax(right = List(StringType), agentClassString = "O---", switches = true)),
    ("_importworld", commandSyntax(right = List(StringType), agentClassString = "O---", switches = true)),
    ("_incone", reporterSyntax(precedence = NormalPrecedence + 2, left = TurtlesetType | PatchsetType,
      right = List(NumberType, NumberType), ret = TurtlesetType | PatchsetType, blockAgentClassString = "-T--")),
    ("_inconenowrap", reporterSyntax(precedence = NormalPrecedence + 2, left = AgentsetType,
      right = List(NumberType, NumberType), ret = AgentsetType, blockAgentClassString = "-T--")),
    ("_inlinkfrom", reporterSyntax(right = List(AgentType), ret = AgentType, agentClassString = "-T--")),
    ("_inlinkneighbor", reporterSyntax(right = List(AgentType), ret = BooleanType, agentClassString = "-T--")),
    ("_inlinkneighbors", reporterSyntax(ret = AgentsetType, agentClassString = "-T--")),
    ("_inradius", reporterSyntax(precedence = NormalPrecedence + 2, left = TurtlesetType | PatchsetType,
      right = List(NumberType), ret = TurtlesetType | PatchsetType, agentClassString = "-TP-")),
    ("_inradiusnowrap", reporterSyntax(precedence = NormalPrecedence + 2, left = AgentsetType,
      right = List(NumberType), ret = AgentsetType, agentClassString = "-TP-")),
    ("_inspect", commandSyntax(right = List(AgentType))),
    ("_int", reporterSyntax(right = List(NumberType), ret = NumberType)),
    ("_isagent", reporterSyntax(right = List(WildcardType), ret = BooleanType)),
    ("_isagentset", reporterSyntax(right = List(WildcardType), ret = BooleanType)),
    ("_isboolean", reporterSyntax(right = List(WildcardType), ret = BooleanType)),
    ("_iscommandtask", reporterSyntax(right = List(WildcardType), ret = BooleanType)),
    ("_isdirectedlink", reporterSyntax(right = List(WildcardType), ret = BooleanType)),
    ("_islink", reporterSyntax(right = List(WildcardType), ret = BooleanType)),
    ("_islinkset", reporterSyntax(right = List(WildcardType), ret = BooleanType)),
    ("_islist", reporterSyntax(right = List(WildcardType), ret = BooleanType)),
    ("_isnumber", reporterSyntax(right = List(WildcardType), ret = BooleanType)),
    ("_ispatch", reporterSyntax(right = List(WildcardType), ret = BooleanType)),
    ("_ispatchset", reporterSyntax(right = List(WildcardType), ret = BooleanType)),
    ("_isreportertask", reporterSyntax(right = List(WildcardType), ret = BooleanType)),
    ("_isstring", reporterSyntax(right = List(WildcardType), ret = BooleanType)),
    ("_isturtle", reporterSyntax(right = List(WildcardType), ret = BooleanType)),
    ("_isturtleset", reporterSyntax(right = List(WildcardType), ret = BooleanType)),
    ("_isundirectedlink", reporterSyntax(right = List(WildcardType), ret = BooleanType)),
    ("_item", reporterSyntax(right = List(NumberType, StringType | ListType), ret = WildcardType)),
    ("_jump", commandSyntax(right = List(NumberType), agentClassString = "-T--", switches = true)),
    ("_last", reporterSyntax(right = List(StringType | ListType), ret = WildcardType)),
    ("_layoutcircle", commandSyntax(right = List(ListType | TurtlesetType, NumberType), switches = true)),
    ("_layoutradial", commandSyntax(right = List(TurtlesetType, LinksetType, TurtleType), switches = true)),
    ("_layoutspring", commandSyntax(right = List(TurtlesetType, LinksetType, NumberType, NumberType, NumberType), switches = true)),
    ("_layouttutte", commandSyntax(right = List(TurtlesetType, LinksetType, NumberType), switches = true)),
    ("_left", commandSyntax(right = List(NumberType), agentClassString = "-T--", switches = true)),
    ("_length", reporterSyntax(right = List(StringType | ListType), ret = NumberType)),
    ("_lessorequal", reporterSyntax(precedence = NormalPrecedence - 4, left = AgentType | NumberType | StringType,
      right = List(AgentType | NumberType | StringType), ret = BooleanType)),
    ("_lessthan", reporterSyntax(precedence = NormalPrecedence - 4, left = AgentType | NumberType | StringType,
      right = List(AgentType | NumberType | StringType), ret = BooleanType)),
    ("_let", commandSyntax(right = List(WildcardType, WildcardType))),
    ("_link", reporterSyntax(right = List(NumberType, NumberType), ret = NobodyType | LinkType)),
    ("_linkcode", commandSyntax(agentClassString = "---L")),
    ("_linkheading", reporterSyntax(ret = NumberType, agentClassString = "---L")),
    ("_linklength", reporterSyntax(ret = NumberType, agentClassString = "---L")),
    ("_linkneighbor", reporterSyntax(right = List(AgentType), ret = BooleanType, agentClassString = "-T--")),
    ("_linkneighbors", reporterSyntax(ret = AgentsetType, agentClassString = "-T--")),
    ("_links", reporterSyntax(ret = LinksetType)),
    ("_linkset", reporterSyntax(right = List(ListType | LinksetType | NobodyType | LinkType | RepeatableType),
      ret = LinksetType, defaultOption = Some(1), minimumOption = Some(0))),
    ("_linkshapes", reporterSyntax(ret = ListType)),
    ("_linkwith", reporterSyntax(right = List(AgentType), ret = LinkType, agentClassString = "-T--")),
    ("_list", reporterSyntax(right = List(WildcardType | RepeatableType), ret = ListType, defaultOption = Some(2), minimumOption = Some(0))),
    ("_ln", reporterSyntax(right = List(NumberType), ret = NumberType)),
    ("_log", reporterSyntax(right = List(NumberType, NumberType), ret = NumberType)),
    ("_loop", commandSyntax(right = List(CommandBlockType))),
    ("_lput", reporterSyntax(right = List(WildcardType, ListType), ret = ListType)),
    ("_makepreview", commandSyntax(agentClassString = "O---")),
    ("_map", reporterSyntax(right = List(ReporterTaskType, ListType | RepeatableType), ret = ListType, defaultOption = Some(2))),
    ("_max", reporterSyntax(right = List(ListType), ret = NumberType)),
    ("_maxnof", reporterSyntax(right = List(NumberType, AgentsetType, NumberBlockType), ret = AgentsetType, blockAgentClassString = "?")),
    ("_maxoneof", reporterSyntax(right = List(AgentsetType, NumberBlockType), ret = AgentType, blockAgentClassString = "?")),
    ("_maxpxcor", reporterSyntax(ret = NumberType)),
    ("_maxpycor", reporterSyntax(ret = NumberType)),
    ("_mean", reporterSyntax(right = List(ListType), ret = NumberType)),
    ("_median", reporterSyntax(right = List(ListType), ret = NumberType)),
    ("_member", reporterSyntax(right = List(WildcardType, AgentsetType | StringType | ListType), ret = BooleanType)),
    ("_min", reporterSyntax(right = List(ListType), ret = NumberType)),
    ("_minnof", reporterSyntax(right = List(NumberType, AgentsetType, NumberBlockType), ret = AgentsetType, blockAgentClassString = "?")),
    ("_minoneof", reporterSyntax(right = List(AgentsetType, NumberBlockType), ret = AgentType, blockAgentClassString = "?")),
    ("_minpxcor", reporterSyntax(ret = NumberType)),
    ("_minpycor", reporterSyntax(ret = NumberType)),
    ("_minus", reporterSyntax(precedence = NormalPrecedence - 3, left = NumberType, right = List(NumberType), ret = NumberType)),
    ("_mkdir", commandSyntax(right = List(StringType))),
    ("_mod", reporterSyntax(precedence = NormalPrecedence - 2, left = NumberType, right = List(NumberType), ret = NumberType)),
    ("_modes", reporterSyntax(right = List(ListType), ret = ListType)),
    ("_mousedown", reporterSyntax(ret = BooleanType)),
    ("_mouseinside", reporterSyntax(ret = BooleanType)),
    ("_mousexcor", reporterSyntax(ret = NumberType)),
    ("_mouseycor", reporterSyntax(ret = NumberType)),
    ("_moveto", commandSyntax(right = List(TurtleType | PatchType), agentClassString = "-T--", switches = true)),
    ("_mult", reporterSyntax(precedence = NormalPrecedence - 2, left = NumberType, right = List(NumberType), ret = NumberType)),
    ("_myinlinks", reporterSyntax(ret = LinksetType, agentClassString = "-T--")),
    ("_mylinks", reporterSyntax(ret = LinksetType, agentClassString = "-T--")),
    ("_myoutlinks", reporterSyntax(ret = LinksetType, agentClassString = "-T--")),
    ("_myself", reporterSyntax(ret = AgentType, agentClassString = "-TPL")),
    ("_nanotime", reporterSyntax(ret = NumberType)),
    ("_neighbors", reporterSyntax(ret = PatchsetType, agentClassString = "-TP-")),
    ("_neighbors4", reporterSyntax(ret = PatchsetType, agentClassString = "-TP-")),
    ("_netlogoapplet", reporterSyntax(ret = BooleanType)),
    ("_netlogoversion", reporterSyntax(ret = StringType)),
    ("_newseed", reporterSyntax(ret = NumberType)),
    ("_nodisplay", commandSyntax()),
    ("_nof", reporterSyntax(right = List(NumberType, AgentsetType | ListType), ret = AgentsetType | ListType)),
    ("_nolinks", reporterSyntax(ret = LinksetType)),
    ("_nopatches", reporterSyntax(ret = PatchsetType)),
    ("_not", reporterSyntax(right = List(BooleanType), ret = BooleanType)),
    ("_notequal", reporterSyntax(precedence = NormalPrecedence - 5, left = WildcardType, right = List(WildcardType), ret = BooleanType)),
    ("_noturtles", reporterSyntax(ret = TurtlesetType)),
    ("_nvalues", reporterSyntax(right = List(NumberType, ReporterTaskType), ret = ListType)),
    ("_observercode", commandSyntax(agentClassString = "O---")),
    ("_of", reporterSyntax(precedence = NormalPrecedence + 1, left = ReporterBlockType, right = List(AgentsetType | AgentType),
      ret = WildcardType, isRightAssociative = true, blockAgentClassString = "?")),
    ("_oneof", reporterSyntax(right = List(AgentsetType | ListType), ret = WildcardType)),
    ("_or", reporterSyntax(precedence = NormalPrecedence - 6, left = BooleanType, right = List(BooleanType), ret = BooleanType)),
    ("_other", reporterSyntax(right = List(AgentsetType), ret = AgentsetType)),
    ("_otherend", reporterSyntax(ret = AgentType, agentClassString = "-T-L")),
    ("_outlinkneighbor", reporterSyntax(right = List(AgentType), ret = BooleanType, agentClassString = "-T--")),
    ("_outlinkneighbors", reporterSyntax(ret = AgentsetType, agentClassString = "-T--")),
    ("_outlinkto", reporterSyntax(right = List(AgentType), ret = AgentType, agentClassString = "-T--")),
    ("_outputprint", commandSyntax(right = List(WildcardType))),
    ("_outputshow", commandSyntax(right = List(WildcardType))),
    ("_outputtype", commandSyntax(right = List(WildcardType))),
    ("_outputwrite", commandSyntax(right = List(WildcardType))),
    ("_patch", reporterSyntax(right = List(NumberType, NumberType), ret = NobodyType | PatchType)),
    ("_patchahead", reporterSyntax(right = List(NumberType), ret = PatchType, agentClassString = "-T--")),
    ("_patchat", reporterSyntax(right = List(NumberType, NumberType), ret = NobodyType | PatchType, agentClassString = "-TP-")),
    ("_patchatheadinganddistance", reporterSyntax(right = List(NumberType, NumberType), ret = PatchType, agentClassString = "-TP-")),
    ("_patchcode", commandSyntax(agentClassString = "--P-")),
    ("_patchcol", reporterSyntax(right = List(NumberType), ret = PatchsetType)),
    ("_patches", reporterSyntax(ret = PatchsetType)),
    ("_patchhere", reporterSyntax(ret = PatchType, agentClassString = "-T--")),
    ("_patchleftandahead", reporterSyntax(right = List(NumberType, NumberType), ret = PatchType, agentClassString = "-T--")),
    ("_patchrightandahead", reporterSyntax(right = List(NumberType, NumberType), ret = PatchType, agentClassString = "-T--")),
    ("_patchrow", reporterSyntax(right = List(NumberType), ret = PatchsetType)),
    ("_patchset", reporterSyntax(right = List(ListType | PatchsetType | NobodyType | PatchType | RepeatableType),
      ret = PatchsetType, defaultOption = Some(1), minimumOption = Some(0))),
    ("_patchsize", reporterSyntax(ret = NumberType)),
    ("_pendown", commandSyntax(agentClassString = "-T--", switches = true)),
    ("_penerase", commandSyntax(agentClassString = "-T--", switches = true)),
    ("_penup", commandSyntax(agentClassString = "-T--", switches = true)),
    ("_plot", commandSyntax(right = List(NumberType))),
    ("_plotname", reporterSyntax(ret = StringType)),
    ("_plotpendown", commandSyntax()),
    ("_plotpenexists", reporterSyntax(right = List(StringType), ret = BooleanType)),
    ("_plotpenhide", commandSyntax()),
    ("_plotpenreset", commandSyntax()),
    ("_plotpenshow", commandSyntax()),
    ("_plotpenup", commandSyntax()),
    ("_plotxmax", reporterSyntax(ret = NumberType)),
    ("_plotxmin", reporterSyntax(ret = NumberType)),
    ("_plotxy", commandSyntax(right = List(NumberType, NumberType))),
    ("_plotymax", reporterSyntax(ret = NumberType)),
    ("_plotymin", reporterSyntax(ret = NumberType)),
    ("_plus", reporterSyntax(precedence = NormalPrecedence - 3, left = NumberType, right = List(NumberType), ret = NumberType)),
    ("_position", reporterSyntax(right = List(WildcardType, StringType | ListType), ret = NumberType | BooleanType)),
    ("_pow", reporterSyntax(precedence = NormalPrecedence - 1, left = NumberType, right = List(NumberType), ret = NumberType)),
    ("_precision", reporterSyntax(right = List(NumberType, NumberType), ret = NumberType)),
    ("_print", commandSyntax(right = List(WildcardType))),
    ("_processors", reporterSyntax(ret = NumberType)),
    ("_pwd", commandSyntax(agentClassString = "O---")),
    ("_random", reporterSyntax(right = List(NumberType), ret = NumberType)),
    ("_randomexponential", reporterSyntax(right = List(NumberType), ret = NumberType)),
    ("_randomfloat", reporterSyntax(right = List(NumberType), ret = NumberType)),
    ("_randomgamma", reporterSyntax(right = List(NumberType, NumberType), ret = NumberType)),
    ("_randomnormal", reporterSyntax(right = List(NumberType, NumberType), ret = NumberType)),
    ("_randompoisson", reporterSyntax(right = List(NumberType), ret = NumberType)),
    ("_randompxcor", reporterSyntax(ret = NumberType)),
    ("_randompycor", reporterSyntax(ret = NumberType)),
    ("_randomseed", commandSyntax(right = List(NumberType))),
    ("_randomstate", reporterSyntax(ret = StringType)),
    ("_randomxcor", reporterSyntax(ret = NumberType)),
    ("_randomycor", reporterSyntax(ret = NumberType)),
    ("_readfromstring", reporterSyntax(right = List(StringType), ret = ReadableType)),
    ("_reduce", reporterSyntax(right = List(ReporterTaskType, ListType), ret = WildcardType)),
    ("_reloadextensions", commandSyntax(switches = true)),
    ("_remainder", reporterSyntax(right = List(NumberType, NumberType), ret = NumberType)),
    ("_remove", reporterSyntax(right = List(WildcardType, StringType | ListType), ret = StringType | ListType)),
    ("_removeduplicates", reporterSyntax(right = List(ListType), ret = ListType)),
    ("_removeitem", reporterSyntax(right = List(NumberType, StringType | ListType), ret = StringType | ListType)),
    ("_repeat", commandSyntax(right = List(NumberType, CommandBlockType))),
    ("_replaceitem", reporterSyntax(right = List(NumberType, StringType | ListType, WildcardType), ret = StringType | ListType)),
    ("_report", commandSyntax(right = List(WildcardType))),
    ("_resetperspective", commandSyntax(switches = true)),
    ("_resetticks", commandSyntax(agentClassString = "O---", switches = true)),
    ("_resettimer", commandSyntax()),
    ("_resizeworld", commandSyntax(right = List(NumberType, NumberType, NumberType, NumberType), agentClassString = "O---", switches = true)),
    ("_reverse", reporterSyntax(right = List(StringType | ListType), ret = StringType | ListType)),
    ("_rgb", reporterSyntax(right = List(NumberType, NumberType, NumberType), ret = ListType)),
    ("_ride", commandSyntax(right = List(TurtleType), agentClassString = "O---", switches = true)),
    ("_rideme", commandSyntax(agentClassString = "-T--", switches = true)),
    ("_right", commandSyntax(right = List(NumberType), agentClassString = "-T--", switches = true)),
    ("_round", reporterSyntax(right = List(NumberType), ret = NumberType)),
    ("_run", commandSyntax(right = List(StringType | CommandTaskType, WildcardType | RepeatableType), defaultOption = Some(1))),
    ("_runresult", reporterSyntax(right = List(StringType | ReporterTaskType, WildcardType | RepeatableType), ret = WildcardType, defaultOption = Some(1))),
    ("_scalecolor", reporterSyntax(right = List(NumberType, NumberType, NumberType, NumberType), ret = NumberType)),
    ("_self", reporterSyntax(ret = AgentType, agentClassString = "-TPL")),
    ("_sentence", reporterSyntax(right = List(WildcardType | RepeatableType), ret = ListType, defaultOption = Some(2), minimumOption = Some(0))),
    ("_set", commandSyntax(right = List(WildcardType, WildcardType))),
    ("_setcurdir", commandSyntax(right = List(StringType))),
    ("_setcurrentplot", commandSyntax(right = List(StringType))),
    ("_setcurrentplotpen", commandSyntax(right = List(StringType))),
    ("_setdefaultshape", commandSyntax(right = List(TurtlesetType | LinksetType, StringType), agentClassString = "O---")),
    ("_sethistogramnumbars", commandSyntax(right = List(NumberType))),
    ("_setlinethickness", commandSyntax(right = List(NumberType), agentClassString = "-T--", switches = true)),
    ("_setpatchsize", commandSyntax(right = List(NumberType), agentClassString = "O---", switches = true)),
    ("_setplotpencolor", commandSyntax(right = List(NumberType))),
    ("_setplotpeninterval", commandSyntax(right = List(NumberType))),
    ("_setplotpenmode", commandSyntax(right = List(NumberType))),
    ("_setplotxrange", commandSyntax(right = List(NumberType, NumberType))),
    ("_setplotyrange", commandSyntax(right = List(NumberType, NumberType))),
    ("_setupplots", commandSyntax()),
    ("_setxy", commandSyntax(right = List(NumberType, NumberType), agentClassString = "-T--", switches = true)),
    ("_shadeof", reporterSyntax(right = List(NumberType, NumberType), ret = BooleanType)),
    ("_shapes", reporterSyntax(ret = ListType)),
    ("_show", commandSyntax(right = List(WildcardType))),
    ("_showlink", commandSyntax(agentClassString = "---L", switches = true)),
    ("_showturtle", commandSyntax(agentClassString = "-T--", switches = true)),
    ("_shuffle", reporterSyntax(right = List(ListType), ret = ListType)),
    ("_sin", reporterSyntax(right = List(NumberType), ret = NumberType)),
    ("_sort", reporterSyntax(right = List(AgentsetType | ListType), ret = ListType)),
    ("_sortby", reporterSyntax(right = List(ReporterTaskType, AgentsetType | ListType), ret = ListType, blockAgentClassString = "?")),
    ("_sorton", reporterSyntax(right = List(ReporterBlockType, AgentsetType), ret = ListType, blockAgentClassString = "?")),
    ("_sprout", commandSyntax(right = List(NumberType, CommandBlockType | OptionalType), agentClassString = "--P-",
      blockAgentClassString = "-T--", switches = true)),
    ("_sqrt", reporterSyntax(right = List(NumberType), ret = NumberType)),
    ("_stacktrace", reporterSyntax(ret = StringType)),
    ("_stamp", commandSyntax(agentClassString = "-T-L", switches = true)),
    ("_stamperase", commandSyntax(agentClassString = "-T-L", switches = true)),
    ("_standarddeviation", reporterSyntax(right = List(ListType), ret = NumberType)),
    ("_stderr", commandSyntax(right = List(WildcardType))),
    ("_stdout", commandSyntax(right = List(WildcardType))),
    ("_stop", commandSyntax()),
    ("_subject", reporterSyntax(ret = AgentType)),
    ("_sublist", reporterSyntax(right = List(ListType, NumberType, NumberType), ret = ListType)),
    ("_substring", reporterSyntax(right = List(StringType, NumberType, NumberType), ret = StringType)),
    ("_subtractheadings", reporterSyntax(right = List(NumberType, NumberType), ret = NumberType)),
    ("_sum", reporterSyntax(right = List(ListType), ret = NumberType)),
    ("_tan", reporterSyntax(right = List(NumberType), ret = NumberType)),
    ("_task", reporterSyntax(right = List(CommandTaskType | ReporterTaskType), ret = CommandTaskType | ReporterTaskType)),
    ("_thunkdidfinish", commandSyntax()),
    ("_tick", commandSyntax(agentClassString = "O---", switches = true)),
    ("_tickadvance", commandSyntax(right = List(NumberType), agentClassString = "O---", switches = true)),
    ("_ticks", reporterSyntax(ret = NumberType)),
    ("_tie", commandSyntax(agentClassString = "---L", switches = true)),
    ("_timer", reporterSyntax(ret = NumberType)),
    ("_tostring", reporterSyntax(right = List(WildcardType), ret = StringType)),
    ("_towards", reporterSyntax(right = List(TurtleType | PatchType), ret = NumberType, agentClassString = "-TP-")),
    ("_towardsnowrap", reporterSyntax(right = List(TurtleType | PatchType), ret = NumberType, agentClassString = "-TP-")),
    ("_towardsxy", reporterSyntax(right = List(NumberType, NumberType), ret = NumberType, agentClassString = "-TP-")),
    ("_towardsxynowrap", reporterSyntax(right = List(NumberType, NumberType), ret = NumberType, agentClassString = "-TP-")),
    ("_turtle", reporterSyntax(right = List(NumberType), ret = NobodyType | TurtleType)),
    ("_turtlecode", commandSyntax(agentClassString = "-T--")),
    ("_turtles", reporterSyntax(ret = TurtlesetType)),
    ("_turtlesat", reporterSyntax(right = List(NumberType, NumberType), ret = TurtlesetType, agentClassString = "-TP-")),
    ("_turtleset", reporterSyntax(right = List(ListType | TurtlesetType | NobodyType | TurtleType | RepeatableType),
      ret = TurtlesetType, defaultOption = Some(1), minimumOption = Some(0))),
    ("_turtleshere", reporterSyntax(ret = TurtlesetType, agentClassString = "-TP-")),
    ("_turtleson", reporterSyntax(right = List(AgentsetType | AgentType), ret = TurtlesetType)),
    ("_type", commandSyntax(right = List(WildcardType))),
    ("_untie", commandSyntax(agentClassString = "---L", switches = true)),
    ("_updatemonitor", commandSyntax(right = List(WildcardType), agentClassString = "O---", switches = true)),
    ("_updateplots", commandSyntax()),
    ("_uphill", commandSyntax(right = List(ReferenceType), agentClassString = "-T--", switches = true)),
    ("_uphill4", commandSyntax(right = List(ReferenceType), agentClassString = "-T--", switches = true)),
    ("_userdirectory", reporterSyntax(ret = BooleanType | StringType)),
    ("_userfile", reporterSyntax(ret = BooleanType | StringType)),
    ("_userinput", reporterSyntax(right = List(WildcardType), ret = StringType)),
    ("_usermessage", commandSyntax(right = List(WildcardType))),
    ("_usernewfile", reporterSyntax(ret = BooleanType | StringType)),
    ("_useroneof", reporterSyntax(right = List(WildcardType, ListType), ret = WildcardType)),
    ("_useryesorno", reporterSyntax(right = List(WildcardType), ret = BooleanType)),
    ("_variance", reporterSyntax(right = List(ListType), ret = NumberType)),
    ("_wait", commandSyntax(right = List(NumberType))),
    ("_watch", commandSyntax(right = List(AgentType), agentClassString = "O---", switches = true)),
    ("_watchme", commandSyntax(agentClassString = "-TPL", switches = true)),
    ("_while", commandSyntax(right = List(BooleanBlockType, CommandBlockType))),
    ("_with", reporterSyntax(precedence = NormalPrecedence + 2, left = AgentsetType,
      right = List(BooleanBlockType), ret = AgentsetType, blockAgentClassString = "?")),
    ("_withlocalrandomness", commandSyntax(right = List(CommandBlockType))),
    ("_withmax", reporterSyntax(precedence = NormalPrecedence + 2, left = AgentsetType,
      right = List(NumberBlockType), ret = AgentsetType, blockAgentClassString = "?")),
    ("_withmin", reporterSyntax(precedence = NormalPrecedence + 2, left = AgentsetType,
      right = List(NumberBlockType), ret = AgentsetType, blockAgentClassString = "?")),
    ("_withoutinterruption", commandSyntax(right = List(CommandBlockType))),
    ("_word", reporterSyntax(right = List(WildcardType | RepeatableType), ret = StringType, defaultOption = Some(2), minimumOption = Some(0))),
    ("_worldheight", reporterSyntax(ret = NumberType)),
    ("_worldwidth", reporterSyntax(ret = NumberType)),
    ("_wrapcolor", reporterSyntax(right = List(NumberType), ret = NumberType)),
    ("_write", commandSyntax(right = List(WildcardType))),
    ("_xor", reporterSyntax(precedence = NormalPrecedence - 6, left = BooleanType, right = List(BooleanType), ret = BooleanType))
  )
}
