# Only required for making NetLogo releases (via the `dist/*` commands in SBT)
#
# To ignore local changes to this file, use: `git update-index --skip-worktree .jdks.yaml`
#
# To resume tracking local changes to this file, use the `--no-skip-worktree` flag instead.
#
# Example content:
#
# - vendor:       "Liberica"
#   version:      "17.0.15"
#   architecture: "32"
#   path:         "/my/favorite/jdk-store/liberica-jdk-17.0.15/"
#
# - vendor:       "OpenJDK"
#   version:      "17.0.2"
#   architecture: "64"
#   path:         "/my/favorite/jdk-store/jdk-17.0.2/"
#
#
# NOTE: Even on Windows, you need to use '/' as your directory separator, not '\'!
