// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {tracker, keywords} from "./keywords.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "*hQYQPOOOwQPO'#D^O!PQPO'#D^O!UQPO'#D^O!ZQPO'#D^O!`QPO'#D^OOQO'#DR'#DRQYQPOOO!eQQO'#D_O!jQSO'#D_OOQO'#DW'#DWQ!oQPOOO!wQPO'#CrO#PQPO,59xO#tQPO,59xO#yQPO'#CsOOQO,59x,59xO$RQWO'#CtO$ZQPO'#CvO$cQSO'#CxOOQO-E7P-E7PO$hQPO,59yOOQO-E7U-E7UO$yQPO'#DSO%UQPO,59^OOQO,59^,59^O%^QPO1G/dOOQO'#DT'#DTO%cQPO,59_OOQO,59_,59_OOQO'#DU'#DUO%kQWO,59`OOQO,59`,59`OOQO'#DV'#DVO%sQPO,59bOOQO,59b,59bO%{QSO,59dO&cQPO'#DPO&jQPO'#DOOOQO'#D`'#D`O&xQPO'#D`OOQO'#DX'#DXO'mQPO1G/eOOQO1G/e1G/eO'mQPO1G/eO(OQPO,59nOOQO-E7Q-E7QOOQO1G.x1G.xOOQO7+%O7+%OOOQO-E7R-E7ROOQO1G.y1G.yOOQO-E7S-E7SOOQO1G.z1G.zOOQO-E7T-E7TOOQO1G.|1G.|O(TQPO1G/OO(YQPO,59gO&QQPO'#DPOOQO,59k,59kO(bQPO,59kO(sQPO,59jOOQO'#DY'#DYO)UQPO,59zOOQO-E7V-E7VOOQO7+%P7+%PO)yQPO7+%POOQO1G/Y1G/YOOQO7+$j7+$jOOQO1G/R1G/ROOQO1G/V1G/VOOQO1G/U1G/UOOQO-E7W-E7WOOQO<<Hk<<Hk",
  stateData: "*_~O!POSaOS~OPPOQQOTROUQOVSOWTOXWOYXO[RO~Oc]Oe[O~Oe_O~OeaO~OebO~OecO~OneO~OmeO~OXWOYXO~OcgOdiO~OSjOP!QaQ!QaT!QaU!QaV!QaW!QaX!QaY!Qa[!Qa}!Qa~ORjO~OckOdmO~OdpOinO~OdsOkqO~OmtO~OZ{O]xO^xOeuOqvO~OS}OcvXdvX~OcgOd!PO~Oc!QO~OckOd!SO~Od!UOinO~Od!WOkqO~Om!XO~O]xO^xOd![Oe!ZOqvO~OckO~P&QO]xO^xOe!ZOqvO~O`!_Oc!_Ok!_Ot!_OZ!SX]!SX^!SXe!SXq!SXd!SXp!SX~OZ!bO]xO^xOe!ZOqvO~Oc!dO~Od!eO~OckOd!fO~O]xO^xOd!gOe!ZOqvO~O]xO^xOe!ZOp!hOqvO~O`!_Oc!_Ok!_Ot!_OZ!Sa]!Sa^!Sae!Saq!Sad!Sap!Sa~OZ!jO]xO^xOe!ZOqvO~Otc~",
  goto: "$m!TPPPPPPPPPPPPPPPPPPPPPP!U!X![P!_P!bPP!ePP!h!hP!s!y#P#Z#a#g#n$RPPP$X$]$bR^PR`QR`RR`SR`TR|ecweuvz|!Z!]!^!cQVORdVQh[R!OhQl_S!Rl!YR!YuQoaR!ToQrbR!VrSZOVRfZQzeS!]u!ZQ!^vW!az!]!^!cR!c|Q!`xR!i!`TUOVVYOVZcyeuvz|!Z!]!^!c",
  nodeNames: "⚠ Import Export From As Globals Extensions Includes Breed To ToReport End Own Command Reporter Var Constant Comment Program Identifier CloseBracket OpenBracket ImportBlock IdentBlock VarBlock AlwaysVar StringBlock String BreedBlock AlwaysReporter AlwaysCommand InputBlock CloseParen OpenParen ParenExpression BracketExpression Number",
  maxTerm: 50,
  context: tracker,
  nodeProps: [
    ["openedBy", 17,";",20,"OpenBracket",32,"OpenParen"],
    ["closedBy", 21,"CloseBracket",33,"CloseParen"]
  ],
  skippedNodes: [0,15,17],
  repeatNodeCount: 8,
  tokenData: "6Z~RuX^#fpq#fqr$Zrs%wst$Ztu$Zuv$Zvw$Zwx$Zxy(fyz(kz{$Z{|$Z}!O(p!O!P$Z!P!Q$Z!Q![4`![!]$Z!]!^5h!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z!}#O6P#P#Q6U#Q#R$Z#R#S$Z#T#o$Z#y#z#f$f$g#f#BY#BZ#f$IS$I_#f$I|$JO#f$JT$JU#f$KV$KW#f&FU&FV#f~#kY!P~X^#fpq#f#y#z#f$f$g#f#BY#BZ#f$IS$I_#f$I|$JO#f$JT$JU#f$KV$KW#f&FU&FV#f_$fenQmSiWcPqr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![$Z![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$Z~%zZOY%wYZ&mZr%wrs&ms#O%w#O#P&r#P;'S%w;'S;=`(`<%l~%w~O%w~~&m~&rOk~~&uZOY%wYZ&mZr%wrs'hs#O%w#O#P&r#P;'S%w;'S;=`(`<%l~%w~O%w~~&m~'mZk~OY%wYZ&mZr%wrs&ms#O%w#O#P&r#P;'S%w;'S;=`(`<%l~%w~O%w~~&m~(cP;=`<%l%w~(kOq~~(pOp~_({enQmSiWcPqr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![*^![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$Z_*kgnQmSiWtPcPqr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P,S!P!Q$Z!Q![*^![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#X$Z#X#Y/f#Y#o$Z_,_enQmSiWcPqr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![-p![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$Z_-}gnQmSiWtPcPqr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![-p![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#X$Z#X#Y/f#Y#o$Z_/qenQmSiWcPqr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|1S}!O1S!O!P$Z!P!Q$Z!Q![$Z![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$Z_1_enQmSiWcPqr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![2p![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$Z_2}enQmSiWtPcPqr$Zst$Ztu$Zuv$Zvw$Zwx$Zz{$Z{|$Z}!O$Z!O!P$Z!P!Q$Z!Q![2p![!]$Z!^!_$Z!_!`$Z!`!a$Z!a!b$Z!c!}$Z#Q#R$Z#R#S$Z#T#o$ZP4eRtP!O!P4n!Q![4`#X#Y5PP4qP!Q![4tP4yQtP!Q![4t#X#Y5PP5SQ{|5Y}!O5YP5]P!Q![5`P5ePtP!Q![5`~5mSa~OY5hZ;'S5h;'S;=`5y<%lO5h~5|P;=`<%l5h~6UOe~~6ZOd~",
  tokenizers: [0, 1, 2, 3],
  topRules: {"Program":[0,18]},
  specialized: [{term: 19, get: (value: any, stack: any) => (keywords(value, stack) << 1), external: keywords}],
  tokenPrec: 426
})
