package org.nlogo.plot

import scala.collection.mutable.{ Buffer, Subscriber }

/**
 * A PlotActionBuffer logs all plotting actions
 * generated by the supplied PlotManager. Actions
 * can be grabbed (which clears the buffer) and the
 * buffer can be cleared independently.
 * Currently used in the ReviewTab. NP 2013-01-17.
 */
class PlotActionBuffer(plotManager: PlotManager)
  extends Subscriber[PlotAction, PlotManager#Pub] {

  plotManager.subscribe(this)

  val buffer = Buffer[PlotAction]()
  def notify(pub: PlotManager#Pub, action: PlotAction) {
    buffer += action
  }
  def clear() = buffer.clear()
  def grab() = {
    val actions = buffer.toSeq
    clear()
    actions
  }
}
