package org.nlogo.mirror

import scala.collection.mutable

trait Action

trait ActionRunner[A <: Action] {
  def run(action: A): Unit
}

trait ActionBroker[A <: Action]
  extends mutable.Publisher[A] {
  val runner: ActionRunner[A]
  override def publish(action: A) {
    super.publish(action)
    runner.run(action)
  }
}

/**
 * An ActionBuffer logs all plotting actions
 * generated by the supplied ActionBroker. Actions
 * can be grabbed (which clears the buffer) and the
 * buffer can be cleared independently.
 * Currently used in the ReviewTab. NP 2013-01-25.
 */
class ActionBuffer[A <: Action](broker: ActionBroker[A])
  extends mutable.Subscriber[A, ActionBroker[A]#Pub] {
  broker.subscribe(this)
  val buffer = mutable.Buffer[A]()
  def notify(pub: ActionBroker[A]#Pub, action: A) {
    buffer += action
  }
  def clear() = buffer.clear()
  def grab() = {
    val actions = buffer.toSeq
    clear()
    actions
  }
}