// (C) Uri Wilensky. https://github.com/NetLogo/NetLogo

package org.nlogo.mc

import java.awt.image.BufferedImage

import scala.util.Failure
import scala.util.Success

import org.nlogo.api.CompilerException
import org.nlogo.workspace.CurrentModelOpener
import org.nlogo.workspace.PreviewCommandsRunner
import org.nlogo.workspace.WorkspaceFactory

object ImageGenerator {

  def getAutoGeneratedModelImage(workspaceFactory: WorkspaceFactory with CurrentModelOpener): Image =
    new Image() {
      override def getImage(): BufferedImage =
        PreviewCommandsRunner.fromFactory(workspaceFactory).previewImage match {
          case Success(image) => image
          case Failure(e: CompilerException) => throw new ImageException(
            "The Preview Commands for your model do not compile. " +
              "Please use the Preview Commands Editor to change them.", e)
          case Failure(e) => throw e
        }
    }
}
