name: build-and-test

on:
  push:
  # This should change back to simply `pull_request`, once Helio is no longer private.
  # We need to do `pull_request_target`, so people's PRs can get the private token to
  # clone Helio. --Jason B. (3/2/26)
  pull_request_target:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ 'pull_request' != github.event_name || (github.event.pull_request.head.repo.git_url != github.event.pull_request.base.repo.git_url) }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.13.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.HELIO_TOKEN }}

      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21.0.2
          java-package: jdk+fx
          cache: sbt

      - uses: sbt/setup-sbt@v1

      - uses: mfinelli/setup-imagemagick@v7

      - name: Test
        run: |
          export DISPLAY=:0
          Xvfb :0 -screen 0 1920x1080x24 &
          sbt "netlogo/testOnly *RoundTripTests"

      - uses: actions/cache@v5
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
